config/routes.rb
Rails.application.routes.draw do
  root "customers/home#index"
  get     "login"    => "sessions#new"
  post    "login"    => "sessions#create"
  delete  "logout"   => "sessions#destroy"
  
  resources :users

  get "contact" => "customers/static_pages#contact"
  get "error" => "customers/static_pages#error"
  get "index" => "customers/home#index"
  namespace :customers do
    resources :categories, only: [:index, :show]
  end
  namespace :admin do
    root "dashboard#index"

    resources :users
    resources :categories
    resources :discounts
    resources :foods
  end
end

app/models/discount.rb
class Discount < ApplicationRecord
  has_many :foods, dependent: :destroy

  validates :discount, presence: true, uniqueness: true, numericality: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/controllers/admin/discounts_controller.rb
class Admin::DiscountsController < Admin::BaseController
  before_action :find_discount, only: %i(edit update)

  def index
    @discounts = Discount.page params[:page]
  end

  def new
    @discount = Discount.new
  end

  def create
    @discount = Discount.new discount_params

    if @discount.save
      flash[:success] = t ".success"
      redirect_to admin_discounts_path
    else
      flash.now[:danger] = t ".failed"
      render :new
    end
  end

  def edit; end

  def update  
    if @discount.update_attributes discount_params
      flash[:success] = t ".success"
      redirect_to admin_discounts_path
    else
      flash.now[:danger] = t ".failed"
      render :edit
    end
  end

  def destroy
    discount = Discount.find_by id: params[:id]
    if discount.destroy
      flash[:success] = t ".success"
    else
      flash[:warning] = t ".failed"
    end
    redirect_to admin_discounts_path
  end

  private
  
  def discount_params
    params.require(:discount).permit :discount, :start_date, :end_date
  end

  def find_discount
    @discount = Discount.find_by id: params[:id]
    unless @discount
      flash[:warning] = t ".id_blank"
      redirect_to admin_discounts_path
    end
  end
end

app/views/admin/discounts/_discount.html.erb
<tr>
  <td class="text-center"><%= discount.id %></td>
  <td class="text-center"><%= discount.discount %></td>
  <td class="text-center"><%= discount.start_date %></td>
  <td class="text-center"><%= discount.end_date %></td>
  <td class="text-center">
    <%= link_to edit_admin_discount_path(discount),
      class: "mike-action mike-action-edit" do %>
      <i class="fa fa-pencil"></i>
    <% end %>
  </td>
  <td class="text-center">
    <%= link_to admin_discount_path(discount), method: :delete,
      class: "mike-action mike-action-delete",
      data: {confirm: t("admin.users._user.confirm_delete")} do %>
      <i class="fa fa-times"></i>
    <% end %>
  </td>
</tr>

app/views/admin/discounts/_form.html.erb
<%= form_for [:admin, @discount], html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :discount, t(".discount"), class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <%= f.text_field :discount, class: "form-control text-center", 
      placeholder: "%" %>
    </div>
  </div>
  <div class="form-group input-daterange">
    <%= f.label :start_date, t(".start_date"), class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <%= f.text_field :start_date, class: "form-control" %>
    </div>
  </div>
  <div class="form-group input-daterange">
    <%= f.label :end_date, t(".end_date"), class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <%= f.text_field :end_date, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-4">
      <%= f.submit t("admin.discounts._form.add"), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/discounts/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t ".edit_discount" %></h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= t ".edit" %>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-6">
            <%= render "form" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/discounts/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t ".list" %></h1>
  </div>
  <div class="col-lg-12">
        <%= link_to new_admin_discount_path, class: "btn btn-primary" do %>
          <span class="glyphicon glyphicon-plus-sign"></span>
          <%= t "add_discount" %>
        <% end %>
      </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= t "admin.users.index.list" %>
      </div>
      <div class="panel-body">
        <table width="100%"
          class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th class="text-center"><%= t "._id" %></th>
              <th class="text-center"><%= t ".discount" %></th>
              <th class="text-center"><%= t ".start_date" %></th>
              <th class="text-center"><%= t ".end_date" %></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <% if @discounts.index.any? %>
          <%= render @discounts %>
          <% else %>
            <tr>
              <td colspan="4" class="text-center">
                <%= t "admin.users.index.nothing" %>
              </td>
            </tr>
          <% end %>
        </table>
        <div>
          <%= will_paginate %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/discounts/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t ".discount" %></h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= t ".add" %>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12">
            <%= render "form" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>