config/routes.rb
Rails.application.routes.draw do
  root "customers/home#index"
  get     "login"    => "sessions#new"
  post    "login"    => "sessions#create"
  delete  "logout"   => "sessions#destroy"
  
  resources :users

  get "contact" => "customers/static_pages#contact"
  get "error" => "customers/static_pages#error"
  get "index" => "customers/home#index"
  namespace :customers do
    resources :categories, only: [:index, :show]
  end
  namespace :admin do
    root "dashboard#index"

    resources :users
    resources :categories
    resources :discounts
    resources :foods
  end
end

app/views/admin/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"> Footer asdasfjashdifhaskl</h3>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/admin/layouts/_menu.html.erb
<div class="collapse navbar-collapse navbar-ex1-collapse">
  <ul class="nav navbar-nav side-nav">
    <li>
      <%= link_to admin_root_path do %>
        <i class="fa fa-fw fa-dashboard"></i><%= t ".dashboard" %>
      <% end %>
    </li>
    <li>
      <%= link_to admin_categories_path do %>
        <i class="fa fa-fw fa-building-o"></i><%= t ".category" %>
      <% end %>
    </li>
    <li>
      <%= link_to admin_users_path do %>
        <i class="fa fa-fw fa-user-o"></i><%= t ".user" %>
      <% end %>
    </li>
    <li>
      <%= link_to "javascript:;", :data => {:toggle => "collapse", 
        :target => "#demo"} do %>
        <i class="fa fa-fw fa-cutlery"></i><%= t ".food" %>
        <i class="fa fa-fw fa-caret-down"></i>
      <% end %>
      <ul id="demo" class="collapse">
        <li>
          <%= link_to admin_foods_path do %>
            <%= t ".list_food" %>
          <% end %>
        </li>
        <li>
          <%= link_to new_admin_food_path do %>
            <%= t ".add_food" %>
          <% end %>
        </li>
      </ul>
    </li>    
    <li>
      <%= link_to "forms.html" do %>
        <i class="fa fa-fw fa-edit"></i><%= t ".order" %>
      <% end %>
    </li>
    <li>
      <%= link_to admin_discounts_path do %>
        <i class="fa fa-fw fa-caret-square-o-down"></i><%= t ".discount" %>
      <% end %>
    </li>
    <li>
      <%= link_to "forms.html" do %>
        <i class="fa fa-fw fa-comment-o"></i><%= t ".review" %>
      <% end %>
    </li>
  </ul>
</div>

app/views/admin/layouts/_top.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to t(".title_framgia"), admin_root_path, class: "navbar-brand" %>
  </div>
  <!-- Top Menu Items -->
  <ul class="nav navbar-right top-nav">
    <li class="dropdown">
      <%= link_to "#", class: "dropdown-toggle", :data => {:toggle => "dropdown"} do %>
        <i class="fa fa-bell"></i><b class="caret"></b>
      <% end %>
      <ul class="dropdown-menu message-dropdown">
        <li class="message-preview">
          <%= link_to "#", class: "dropdown-toggle", :data => {:toggle => "dropdown"} do %>
            <div class="media">
              <span class="pull-left">
                <%= image_tag "http://placehold.it/50x50", class: "media-object", alt: "" %>
              </span>
              <div class="media-body">
                <h5 class="media-heading"><strong>John Smith</strong>
                </h5>
                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                <p>Lorem ipsum dolor sit amet, consectetur...</p>
              </div>
            </div>
          <% end %>
          <%= link_to "#", class: "dropdown-toggle", :data => {:toggle => "dropdown"} do %>
            <div class="media">
              <span class="pull-left">
                <%= image_tag "http://placehold.it/50x50", class: "media-object", alt: "" %>
              </span>
              <div class="media-body">
                <h5 class="media-heading"><strong>John Smith</strong>
                </h5>
                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                <p>Lorem ipsum dolor sit amet, consectetur...</p>
              </div>
            </div>
          <% end %>
        </li>
        <li class="message-preview">
          <%= link_to "#", class: "dropdown-toggle", :data => {:toggle => "dropdown"} do %>
            <div class="media">
              <span class="pull-left">
                <%= image_tag "http://placehold.it/50x50", class: "media-object", alt: "" %>
              </span>
              <div class="media-body">
                <h5 class="media-heading"><strong>John Smith</strong>
                </h5>
                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                <p>Lorem ipsum dolor sit amet, consectetur...</p>
              </div>
            </div>
          <% end %>
        </li>
        <li class="message-preview">
          <%= link_to "#", class: "dropdown-toggle", :data => {:toggle => "dropdown"} do %>
            <div class="media">
              <span class="pull-left">
                <%= image_tag "http://placehold.it/50x50", class: "media-object", alt: "" %>
              </span>
              <div class="media-body">
                <h5 class="media-heading"><strong>John Smith</strong>
                </h5>
                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                <p>Lorem ipsum dolor sit amet, consectetur...</p>
              </div>
            </div>
          <% end %>
        </li>
        <li class="message-footer">
          <a href="#"><%= t ".all_messages" %></a>
        </li>
      </ul>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-user"><%= t ".profile" %></i>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-gear"><%= t ".settings" %></i>
          <% end %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-power-off"><%= t ".logout" %></i>
          <% end %>
        </li>
      </ul>
    </li>
  </ul>
  <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
  <%= render "admin/layouts/menu" %>
  <!-- /.navbar-collapse -->
</nav>