config/routes.rb
Rails.application.routes.draw do
  root "customers/home#index"
  get     "login"    => "sessions#new"
  post    "login"    => "sessions#create"
  delete  "logout"   => "sessions#destroy"
  
  resources :users

  get "contact" => "customers/static_pages#contact"
  get "error" => "customers/static_pages#error"
  get "index" => "customers/home#index"
  namespace :customers do
    resources :categories, only: [:index, :show]
  end
  namespace :admin do
    root "dashboard#index"

    resources :users
    resources :categories
    resources :discounts
    resources :foods
  end
end

app/views/layouts/_footer.html.erb
<footer id="footer"><!--Footer-->
  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col-sm-2">
          <div class="companyinfo">
            <h2><span>e</span><%= t ".shopper" %></h2>
          </div>
        </div>
        <div class="col-sm-7">
          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag("home/ca_1.jpeg", :alt => "iframe1") %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>
          
          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag("home/ga_1.jpeg", :alt => "iframe2") %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>
          
          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag("home/b.jpeg", :alt => "iframe3") %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>
          
          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag("home/changa.jpeg", :alt => "iframe4") %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="address">
            <%= image_tag("home/map.png", :alt => "map") %>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <div class="footer-widget">
    <div class="container">
      <div class="row">
        <div class="col-sm-2">
          <div class="single-widget">
            <h2><%= t ".Service" %></h2>
            <ul class="nav nav-pills nav-stacked">
              <li><%= link_to("Online Help", "#.") %></li>
              <li><%= link_to("Contact Us", "#.") %></li>
              <li><%= link_to("Order Status", "#.") %></li>
              <li><%= link_to("Change Location", "#.") %></li>
              <li><%= link_to("FAQ’s", "#.") %></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2><%= t ".Quock_Shop" %></h2>
            <ul class="nav nav-pills nav-stacked">
              <li><%= link_to("T-Shirt", "#.") %></li>
              <li><%= link_to("Mens", "#.") %></li>
              <li><%= link_to("Womens", "#.") %></li>
              <li><%= link_to("Gift Cards", "#.") %></li>
              <li><%= link_to("Shoes", "#.") %></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2><%= t ".Policies" %></h2>
            <ul class="nav nav-pills nav-stacked">
              <li><%= link_to("Terms of Use", "#.") %></li>
              <li><%= link_to("Privecy Policy", "#.") %></li>
              <li><%= link_to("Refund Policy", "#.") %></li>
              <li><%= link_to("Billing System", "#.") %></li>
              <li><%= link_to("Ticket System", "#.") %></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2><%= t ".About_Shopper" %></h2>
            <ul class="nav nav-pills nav-stacked">
              <li><%= link_to("Company Information", "#.") %></li>
              <li><%= link_to("Careers", "#.") %></li>
              <li><%= link_to("Store Location", "#.") %></li>
              <li><%= link_to("Affillate Program", "#.") %></li>
              <li><%= link_to("Copyright", "#.") %></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3 col-sm-offset-1">
          <div class="single-widget">
            <h2><%= t ".About_Shopper" %></h2>
            <form action="#" class="searchform">
              <input type="text" placeholder="Your email address" />
              <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
            </form>
          </div>
        </div>
        
      </div>
    </div>
  </div>
  
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <p class="pull-left"><%= t ".Designed_by_hello" %></p>
        <p class="pull-right"><%= t ".Designed_by" %><span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
      </div>
    </div>
  </div>  
</footer><!--/Footer-->

app/views/layouts/_header.html.erb
<header id="header"><!--header-->
  <div class="header_top"><!--header_top-->
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <div class="contactinfo">
            <ul class="nav nav-pills">
              <li>
                <%= link_to("#") do %>
                  <i class= "fa fa-phone">+2 95 01 88 821</i>
                <% end %>
              </li>
              <li>
                <%= link_to("#") do %>
                  <i class= "fa fa-envelope">info@domain.com</i>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="social-icons pull-right">
            <ul class="nav navbar-nav">
              <li>
                <%= link_to("#") do %>
                  <i class= "fa fa-facebook"></i>
                <% end %>
              </li>
              <li>
                <%= link_to("#") do %>
                  <i class= "fa fa-twitter"></i>
                <% end %>
              </li>
              <li>
                <%= link_to("#") do %>
                  <i class= "fa fa-linkedin"></i>
                <% end %>
              </li>
              <li>
                <%= link_to("#") do %>
                  <i class= "fa fa-dribbble"></i>
                <% end %>
              </li>
              <li>
                <%= link_to("#") do %>
                  <i class= "fa fa-google-plus"></i>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div><!--/header_top-->
  
  <div class="header-middle"><!--header-middle-->
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <div class="logo pull-left">
            <%= link_to root_path do %>
              <%= image_tag "home/logo.png", :alt => "logo" %>
            <% end %>
          </div>
        </div>
        <div class="col-sm-8">
          <div class="shop-menu pull-right">
            <ul class="nav navbar-nav">
              <% if logged_in? %>
                <li>
                  <%= link_to("#") do %>
                    <i class= "fa fa-user"><%= t ".profile" %></i>
                  <% end %>
                </li>
                <li>
                  <%= link_to("#") do %>
                    <i class= "fa fa-star"><%= t ".wishlist" %></i>
                  <% end %>
                </li>
                <li>
                  <%= link_to("#") do %>
                    <i class= "fa fa-shopping-cart"><%= t ".cart" %></i>
                  <% end %>
                </li>
                <li>                  
                  <%= link_to logout_path, method: :delete do %>
                    <i class= "fa fa-lock"><%= t ".logout" %></i>
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to("#") do %>
                    <i class= "fa fa-shopping-cart"><%= t ".cart" %></i>
                  <% end %>
                </li>
                <li>
                  <%= link_to login_path do %>
                    <i class= "fa fa-lock"><%= t ".login" %></i>
                  <% end %>
                </li>
              <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div><!--/header-middle-->

  <div class="header-bottom"><!--header-bottom-->
    <div class="container">
      <div class="row">
        <div class="col-sm-9">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle"
              data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="mainmenu pull-left">
            <ul class="nav navbar-nav collapse navbar-collapse">
              <li><%= link_to t(".home"), root_path %></li>
              <li class="dropdown">
                <%= link_to "blog.html" do %>
                  <%= t".blog" %><i class= "fa fa-angle-down"></i>
                <% end %>
                <ul role="menu" class="sub-menu">
                  <li><%= link_to t(".blog_List"), "blog.html" %></li>
                  <li><%= link_to t("blog_Single"), "blog-single.html" %></li>
                </ul>
              </li> 
              <li><%= link_to "404", error_path %></li>
              <li><%= link_to t(".contact"), contact_path %></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="search_box pull-right">
            <input type="text" placeholder="Search"/>
          </div>
        </div>
      </div>
    </div>
  </div><!--/header-bottom-->
</header><!--/header-->

app/views/layouts/_slider.html.erb
<section id="slider"><!--slider-->
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div id="slider-carousel" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
            <li data-target="#slider-carousel" data-slide-to="1"></li>
            <li data-target="#slider-carousel" data-slide-to="2"></li>
          </ol>
          
          <div class="carousel-inner">
            <div class="item active">
              <div class="col-sm-6">
                <h1><span>E</span>-SHOPPER</h1>
                <h2>Free E-Commerce Template</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                <button type="button" class="btn btn-default get">Get it now</button>
              </div>
              <div class="col-sm-6">
                <%= image_tag("home/ga_1.jpeg", alt: "girll", class: "girl img-responsive") %>
                <%= image_tag("home/pricing.png", alt: "pricing", class: "pricing") %>
              </div>
            </div>
            <div class="item">
              <div class="col-sm-6">
                <h1><span>E</span>-SHOPPER</h1>
                <h2>100% Responsive Design</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                <button type="button" class="btn btn-default get">Get it now</button>
              </div>
              <div class="col-sm-6">
                <%= image_tag("home/b.jpeg", alt: "girl2", class: "girl img-responsive") %>
                <%= image_tag("home/pricing.png", alt: "pricing", class: "pricing") %>
              </div>
            </div>
            
            <div class="item">
              <div class="col-sm-6">
                <h1><span>E</span>-SHOPPER</h1>
                <h2>Free Ecommerce Template</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                <button type="button" class="btn btn-default get">Get it now</button>
              </div>
              <div class="col-sm-6">
                <%= image_tag("home/changa.jpg", alt: "girl2", class: "girl img-responsive") %>
                <%= image_tag("home/pricing.png", alt: "pricing", class: "pricing") %>
              </div>
            </div>            
          </div>
          <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
            <i class="fa fa-angle-left"></i>
          </a>
          <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
            <i class="fa fa-angle-right"></i>
          </a>
        </div>
        
      </div>
    </div>
  </div>
</section><!--/slider-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <title>SB Admin - Bootstrap Admin Template</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <div id="wrapper">
      <%= render "shared/messages"%>
      <%= render "admin/layouts/top" %>
      <div id="page-wrapper">
        <%= yield %>
      </div>
      <%= render "admin/layouts/footer" %>
    </div>

  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>FramgiaFoodDelivery02</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/messages"%>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>